
services:
  api:
    build: .
    container_name: fastapi_cep
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7
    container_name: redis_cep
    ports:
      - "6380:6379"


  mongo:
    image: mongo:7
    container_name: mongo_cep
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cep_db
